title:   Hunter Walker # your name (or website title) here
logo: "/images/new new - 1.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Developer and Musician.
  <br>
  USFSM Bachelor of Science in Cybersecurity and Information Technology (BSCYS).
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/hunter-walker-7198351a1/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://github.com/HntrWalker/HntrWalker.github.io/blob/master/pdf/Resume_New.pdf">View My Resume</a>
 
  
theme: jekyll-theme-tactile
google_analytics: G-B8C1KDR8MF # your Google Analytics tracking ID here
