title:   Hunter Walker # your name (or website title) here
logo: "/images/new new - 1.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  DEVELOPER AND MUSICIAN
  <br>
  USFSM BACHELOR OF SCIENCE IN CYBERSECURITY (BSCYS)
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/hunter-walker-7198351a1/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
